### ISSUE TITLE
Error processing ICE candidate

### ISSUE THREAD

**Issue by pdxbenjamin** [ajb413/pubnub-js-webrtc#1]
I get an error.
```
WebRTC [peerIceCandidate] error. DOMException: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Error processing ICE candidate

VM279 pubnub-js-webrtc.js:422 
```
I've copied and pasted the few files in your example and published them live.
I have not tested between two computers as this test is just between two browsers on the same pc.

As a result on my two browsers the video/audio and chat all work, I just get this console error. 

any help.
thanks.

**Comment by pdxbenjamin** [comment]
update: I get the same error on your published example.  https://adambavosa.com/pubnub-js-webrtc/example

thanks.

**Comment by ajb413** [comment]
Hey there, I was on vacation but now I am home. Can you tell me which browser you used and which version number? Also if you used incognito or the like. Thanks!
