### ISSUE TITLE
Save the old messages.

### ISSUE THREAD

**Issue by gcarts** [ajb413/pubnub-js-webrtc#2]
Hello.
I know pubnub can store up to 100 old messages for each user. How can I make this script save the old messages?
Best regards

**Comment by ajb413** [comment]
PubNub can store infinite messages. History it is not constrained to users. Go to dashboard.pubnub.com and enable unlimited retention of storage & playback history for your key set.

To get more than 100 messages form the API, try this JavaScript example https://github.com/PubNubDevelopers/pubnub-api-demos-javascript/blob/master/history.html#L64

**Comment by gcarts** [comment]
Hi. Thanks for reply.
I have doing that, but isn t storing yet... I login with a username, than after a few seconds I refresh page and put the same login username, but old messages are cleaned... Here is a print of my key configs:
https://prnt.sc/p1xpst
Best regards

**Comment by ajb413** [comment]
This example in this repo contains code that uses PubNub's Pub/Sub API, but not PubNub's Storage & Playback API. You will need to add code in `app.js` that automatically executes a Storage & Playback API request when the web page loads.

Your new code will retrieve historical messages in the chat. Try using the historical message fetch code from the link I provided above, and remember to use the same channel name from the `publish` and `subscribe` code.

https://github.com/PubNubDevelopers/pubnub-api-demos-javascript/blob/master/history.html#L64

**Comment by gcarts** [comment]
Hi.
Thanks for your super fast response.
I have added:
function messageHandler(status, response) {
    const msgs = response.messages;
    const start = response.startTimeToken;
    const end = response.endTimeToken;
    response.messages.forEach(appendMessageToWebPage);
    if (msgs.length === 100) {
        getAllMessages(start);
    }
}
function getAllMessages(nowJsTimestamp) {
    console.log(nowJsTimestamp);
    if (typeof nowJsTimestamp !== 'string') {
        nowJsTimestamp = new Date().getTime() + '0000';
        container.innerHTML = '';
    }
    pubnub.history({
        channel: [globalChannel],
        start : nowJsTimestamp,
        stringifiedTimeToken: true,
    }, messageHandler);
}

in the end of app.js, but still not works :(

**Comment by ajb413** [comment]
Yes, this is because the new code you have added does not run the `renderMessage` function. Try passing the right data to that method every time there is a new message arriving from PubNub's history.

**Comment by gcarts** [comment]
Hello.
I understand something about javascript, but now it's a bit confusing ... I know I'm asking a lot ... but can you send me the app.js file with the codes inside that you told me?
Best regards

**Comment by ajb413** [comment]
add this on line 236 of `app.js`

```js
pubnub.history({
        channel: globalChannel,
        count: 100,
        stringifiedTimeToken: true
    }, function (status, response) {
        for (let i = 0; i < response.messages.length; i++) {
            response.messages[i].message = response.messages[i].entry;
            delete response.messages[i].entry
        }

        response.messages.forEach(renderMessage);
    });
```

then replace the code on the new line 393 - 395 with this:
```js
    let senderName;

    try {
        senderName = senderUuid === pubnub.getUUID()
            ? username
            : document.getElementById(senderUuid).children[1].innerText;
    } catch (e) {
        senderName = 'unknown';
    }
```

**Comment by gcarts** [comment]
Hi.
Its working, but was you can see, now all old messages show sender: "unknown".
I've seen that you're a professional at PubNub ... I would like to ask if you do custom PubNub-related jobs in exchange for some pay.
Regards

**Comment by gcarts** [comment]
You can contact me at: gracianocoelho83@hotmail.com
